export const teamMembers = [
  {
    id: "1",
    slug: "gregory-colin",
    name: "Grégory Colin",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/GC_1_-_cropped_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/gregorycolin/",
    email: "gregory.colin@alecia.fr",
    formation: "Audencia",
    bureau: "Grand-Ouest",
    bio: "Grégory est diplômé d'Audencia. Il débute sa carrière au sein du groupe Allianz où il exerce durant 7 années des fonctions d'Analyste crédit, d'Auditeur interne et de Contrôleur de gestion. Il rejoint alors les équipes transactionnelles de Deloitte où il intervient pendant 4 ans en tant que Senior Manager et conduit des missions de fusion/acquisition et de due diligence financière. Grégory crée le bureau Grand Ouest d'une banque d'affaires small cap en 2022 avant de co-fonder alecia en 2024. Grégory est par ailleurs membre du comité de sélection du fonds d'amorçage d'Audencia depuis 2022.",
  },
  {
    id: "2",
    slug: "christophe-berthon",
    name: "Christophe Berthon",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/CB_1_-_cropped_-_alt_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/christophe-berthon-843924118/",
    email: "christophe.berthon@alecia.fr",
    formation: "Etudes commerciales",
    bureau: "Sud Est",
    bio: "Après un diplôme de commerce, Christophe débute sa carrière au sein du Groupe Carrefour. Il y évolue pendant 15 ans, occupant successivement des postes fonctionnels notamment aux achats nationaux et régionaux, ainsi qu'opérationnels à des postes de Direction en hypermarchés. Il s'oriente ensuite vers l'entreprenariat et la prestation de services aux entreprises, en créant un groupe qui grandit progressivement à la fois en croissance organique et en croissance externe. Il expérimente alors pour son propre compte les processus de M&A et de levée de fonds en France et en Europe. Après la cession de son groupe il intègre une banque d'affaires small cap en 2019, et y cofonde le bureau de Nice. En 2024, Christophe cofonde alecia, et apporte son expertise en matière de négociation et d'accompagnement des dirigeants sur les opérations de haut de bilan.",
  },
  {
    id: "3",
    slug: "martin-egasse",
    name: "Martin Egasse",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/ME_2_-_cropped_-_alt_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/martinegasse/",
    email: "martin.egasse@alecia.fr",
    formation: "DECG - Université Panthéon-Sorbonne",
    bureau: "Sud Est",
    bio: "Martin est expert-comptable diplômé. Après un parcours académique à l'Université Paris 1 Panthéon-Sorbonne, il débute chez KPMG et intervient pendant 4 ans sur des missions d'expertise-comptable et d'audit légal auprès de TPE, PME et grands comptes. Il évolue ensuite pendant près de 15 ans au sein de différentes PME et ETI où il occupe des postes de Contrôleur de gestion, Responsable ou Directeur financier. Rompu aux situations financières tendues (factoring, procédures collectives, etc.) il accompagne la restructuration ou la cession de plusieurs PME. Martin exerce en tant que conseil en fusion-acquisition depuis plus de 7 ans et cofonde alecia en 2024.",
  },
  {
    id: "4",
    slug: "tristan-cossec",
    name: "Tristan Cossec",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/TC_2_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/tristan-cossec-3b5a0247/",
    email: "tristan.cossec@alecia.fr",
    formation: "EDHEC Business School",
    bureau: "Sud Est",
    bio: "Diplômé de l'EDHEC Business School, Tristan débute sa carrière en fonds d'investissement au sein d'Apax Partners. Il bascule ensuite en conseil en fusion-acquisition, au cours de 3 expériences au sein de boutiques Small & Midcap sur Paris : Eponyme Partners, Equideals et Raphaël Financial Advisory. Tristan intègre ensuite un groupe d'éducation supérieur au poste de M&A et Stratégie. Il rejoint une banque d'affaires small cap en 2022 avant de co-fonder alecia en 2024. Tristan apporte ses compétences techniques et sa maîtrise des process M&A dans des opérations de cession et de LBO/levée de fonds.",
  },
  {
    id: "5",
    slug: "serge-de-fay",
    name: "Serge de Faÿ",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/SF_2_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/serge-de-fa%C3%BF-09713555/",
    email: "serge.defay@alecia.fr",
    formation: "EDHEC Business School, Faculté de Droit de Lille",
    bureau: "Auvergne Rhône Alpes",
    bio: "Serge est diplômé d'un MSc de l'EDHEC Business School et d'un Master 2 en Droit des affaires de l'Université de Lille. Il débute sa carrière en participant à la création de Bolden, prêteur alternatif dédié aux PME françaises. Il occupe les postes de Directeur crédit & produit jusqu'à la cession de la startup à la banque luxembourgeoise RiverBank, dont il créé le bureau français de financements structurés small cap. Serge devient ensuite conseil pour des PME et startups en croissance, avant de rejoindre une banque d'affaires small cap. Il cofonde en 2024 alecia et apporte sa double expertise en finance et direction d'entreprise.",
  },
  {
    id: "6",
    slug: "jerome-berthiau",
    name: "Jérôme Berthiau",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/JB_1_-_cropped_-_alt_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/jeromeberthiau/",
    email: "jerome.berthiau@alecia.fr",
    formation: "EDHEC Business School",
    bureau: "Sud Est",
    bio: "Jérôme est diplômé d'un MSc en finance d'entreprise de l'EDHEC Business School. Après des premières expériences en fusions-acquisitions chez Clearwater puis en dette privée chez LGT, il intègre les équipes de financements structurés de la Société Générale où il participe à de nombreux LBO large-cap en France pendant 2 ans. Il intègre ensuite les équipes de dette privée de Five Arrows, groupe Rothschild & Co, où il participe pendant 6 ans à l'investissement dans une dizaine de sociétés européennes sous format unitranche, dette mezzanine ou PIK Notes. Jérôme est conseil M&A depuis 4 ans, intervenant notamment sur les secteurs tech, santé, industrie et services BtoB. Il cofonde alecia en 2024.",
  },
  {
    id: "7",
    slug: "louise-pini",
    name: "Louise Pini",
    role: "Analyste",
    photo: "/assets/Equipe_Alecia/LP__2__-_cropped.jpg",
    linkedinUrl: "https://www.linkedin.com/in/louise-p-184b7a160/",
    email: "louise.pini@alecia.fr",
    formation: "iaelyon School of Management",
    bureau: "Sud Est",
    bio: "Louise est diplômée du Master Ingénierie Financière et Transaction de l'iaelyon School of Management. Durant son parcours académique, elle cumule différentes expériences dans le secteur financier (coverage large cap chez ING, analyse financière à la Banque de France, audit financier et transaction services dans des cabinets lyonnais). A la fin de ses études, Louise intègre une banque d'affaires indépendante pendant deux ans, puis rejoint alecia en 2024.",
  },
  {
    id: "8",
    slug: "mickael-furet",
    name: "Mickael Furet",
    role: "Analyste",
    photo: "/assets/Equipe_Alecia/MF_p800.jpg",
    linkedinUrl: "https://www.linkedin.com/in/mickael-furet/",
    email: "mickael.furet@alecia.fr",
    formation: "Edhec Business School",
    bureau: "Sud Est",
    bio: "Mickael est étudiant du MiM et du MSc Finance d'Entreprise de l'EDHEC Business School. Il initie son parcours professionnel au CIC en tant que Chargé d'Affaires Entreprises, avant d'exercer en tant qu'Analyste M&A au sein de deux cabinets de conseil en fusions-acquisitions.",
  },
];

export const mockDeals = [
  {
    id: "1",
    slug: "hmr-leclerc",
    clientName: "HMR",
    clientLogo: null,
    acquirerName: "Leclerc - franchisé",
    acquirerLogo: null,
    sector: "Distribution & services B2C",
    region: "Provence-Alpes-Côte d'Azur",
    year: 2022,
    mandateType: "Cession",
    isPriorExperience: false,
  },
  {
    id: "2",
    slug: "safe-group",
    clientName: "Safe Group",
    clientLogo: null,
    acquirerName: "DOGS Security",
    acquirerLogo: null,
    sector: "Distribution & services B2B",
    region: "Île-de-France",
    year: 2024,
    mandateType: "Acquisition",
    isPriorExperience: false,
  },
  {
    id: "3",
    slug: "signes",
    clientName: "Signes",
    clientLogo: null,
    acquirerName: "La/Ba Architectes",
    acquirerLogo: null,
    sector: "Distribution & services B2C",
    region: "Île-de-France",
    year: 2024,
    mandateType: "Cession",
    isPriorExperience: true,
  },
  {
    id: "4",
    slug: "xrl-consulting",
    clientName: "XRL Consulting",
    clientLogo: null,
    acquirerName: "Banque Populaire et Caisse d'Epargne",
    acquirerLogo: null,
    sector: "Distribution & services B2B",
    region: "Île-de-France",
    year: 2023,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "5",
    slug: "kanope",
    clientName: "Kanopé",
    clientLogo: null,
    acquirerName: "Metagram",
    acquirerLogo: null,
    sector: "Services financiers & assurance",
    region: "Occitanie",
    year: 2023,
    mandateType: "Cession",
    isPriorExperience: true,
  },
  {
    id: "6",
    slug: "keller-williams",
    clientName: "Keller Williams",
    clientLogo: null,
    acquirerName: "Entrepreneur Invest",
    acquirerLogo: null,
    sector: "Immobilier & construction",
    region: "Île-de-France",
    year: 2022,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "7",
    slug: "wyz-group",
    clientName: "Wyz Group",
    clientLogo: null,
    acquirerName: "Generis Capital Partners",
    acquirerLogo: null,
    sector: "Technologies & logiciels",
    region: "Hauts-de-France",
    year: 2021,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "8",
    slug: "finaxy",
    clientName: "Finaxy",
    clientLogo: null,
    acquirerName: "Ardian",
    acquirerLogo: null,
    sector: "Services financiers & assurance",
    region: "Île-de-France",
    year: 2021,
    mandateType: "Cession",
    isPriorExperience: true,
  },
];

// Sector verticals with investment thesis (Phase 1 - Roadmap #19-20)
export const mockSectors = [
  {
    id: "1",
    slug: "technologies-logiciels",
    nameFr: "Technologies & logiciels",
    nameEn: "Technology & Software",
    descriptionFr: "Accompagnement des éditeurs de logiciels, ESN, et entreprises tech dans leurs opérations de croissance externe et transmission.",
    descriptionEn: "Supporting software publishers, IT services companies, and tech businesses in their external growth and transmission operations.",
    investmentThesisFr: "Le secteur technologique français connaît une consolidation accélérée. Les multiples de valorisation restent attractifs pour les PME rentables, avec un intérêt croissant des fonds de Private Equity pour le modèle SaaS récurrent. Notre expertise couvre l'ensemble du spectre, des éditeurs traditionnels aux pure players cloud.",
    investmentThesisEn: "The French technology sector is experiencing accelerated consolidation. Valuation multiples remain attractive for profitable SMEs, with growing Private Equity interest in the recurring SaaS model.",
    iconType: "technology",
    referentPartner: "gregory-colin",
  },
  {
    id: "2",
    slug: "distribution-services-b2b",
    nameFr: "Distribution & services B2B",
    nameEn: "B2B Distribution & Services",
    descriptionFr: "Conseil en cession et acquisition pour les acteurs de la distribution professionnelle et des services aux entreprises.",
    descriptionEn: "M&A advisory for professional distribution and B2B services companies.",
    investmentThesisFr: "Le marché B2B français offre des opportunités de consolidation significatives, notamment dans la distribution spécialisée et les services à forte valeur ajoutée. Les acquéreurs privilégient les entreprises avec une récurrence de revenus et une forte fidélisation client.",
    investmentThesisEn: "The French B2B market offers significant consolidation opportunities, particularly in specialized distribution and high value-added services.",
    iconType: "building",
    referentPartner: "christophe-berthon",
  },
  {
    id: "3",
    slug: "distribution-services-b2c",
    nameFr: "Distribution & services B2C",
    nameEn: "B2C Distribution & Services",
    descriptionFr: "Accompagnement des enseignes retail, franchises et acteurs du commerce de détail dans leurs projets de transmission.",
    descriptionEn: "Supporting retail chains, franchises, and retail businesses in their transmission projects.",
    investmentThesisFr: "La transformation digitale du retail crée des opportunités pour les enseignes omnicanales. Les réseaux de franchise restent très recherchés pour leur modèle scalable et leur rentabilité récurrente.",
    investmentThesisEn: "The digital transformation of retail creates opportunities for omnichannel retailers. Franchise networks remain highly sought after for their scalable model.",
    iconType: "shopping",
    referentPartner: "martin-egasse",
  },
  {
    id: "4",
    slug: "sante",
    nameFr: "Santé",
    nameEn: "Healthcare",
    descriptionFr: "Expertise M&A dans le secteur de la santé : cliniques, laboratoires, medtech, et services de santé.",
    descriptionEn: "M&A expertise in healthcare: clinics, laboratories, medtech, and health services.",
    investmentThesisFr: "Le secteur de la santé français est en pleine mutation avec la consolidation des laboratoires d'analyses, le développement des medtech et la restructuration du parc des cliniques privées. Les investisseurs recherchent des actifs défensifs avec une visibilité long terme.",
    investmentThesisEn: "The French healthcare sector is undergoing significant transformation with laboratory consolidation, medtech development, and private clinic restructuring.",
    iconType: "health",
    referentPartner: "tristan-cossec",
  },
  {
    id: "5",
    slug: "immobilier-construction",
    nameFr: "Immobilier & construction",
    nameEn: "Real Estate & Construction",
    descriptionFr: "Conseil en M&A pour promoteurs, entreprises de BTP, et acteurs de l'immobilier professionnel.",
    descriptionEn: "M&A advisory for developers, construction companies, and commercial real estate players.",
    investmentThesisFr: "Malgré les cycles immobiliers, les entreprises de construction spécialisées et les promoteurs régionaux bien positionnés restent attractifs. La transition énergétique ouvre de nouvelles opportunités dans la rénovation et la construction durable.",
    investmentThesisEn: "Despite real estate cycles, specialized construction companies and well-positioned regional developers remain attractive.",
    iconType: "construction",
    referentPartner: "serge-de-fay",
  },
  {
    id: "6",
    slug: "industries",
    nameFr: "Industries",
    nameEn: "Manufacturing & Industry",
    descriptionFr: "Accompagnement des ETI industrielles, sous-traitants et équipementiers dans leurs opérations stratégiques.",
    descriptionEn: "Supporting industrial mid-caps, subcontractors, and equipment manufacturers in their strategic operations.",
    investmentThesisFr: "L'industrie française fait face à des enjeux de transmission générationnelle et de consolidation sectorielle. Les acquéreurs recherchent des savoir-faire différenciants, des positions de marché défendables et des capacités d'export.",
    investmentThesisEn: "French industry faces generational transmission and sector consolidation challenges. Buyers seek differentiating know-how and defensible market positions.",
    iconType: "industry",
    referentPartner: "jerome-berthiau",
  },
  {
    id: "7",
    slug: "services-financiers-assurance",
    nameFr: "Services financiers & assurance",
    nameEn: "Financial Services & Insurance",
    descriptionFr: "Expertise sectorielle pour courtiers, CGP, fintech et acteurs de l'assurance.",
    descriptionEn: "Sector expertise for brokers, wealth managers, fintech, and insurance players.",
    investmentThesisFr: "Le secteur financier connaît une consolidation intense, alimentée par la pression réglementaire et la digitalisation. Les cabinets de courtage et de gestion de patrimoine avec une base clients fidèle sont particulièrement recherchés.",
    investmentThesisEn: "The financial sector is experiencing intense consolidation, driven by regulatory pressure and digitalization.",
    iconType: "finance",
    referentPartner: "gregory-colin",
  },
  {
    id: "8",
    slug: "agroalimentaire",
    nameFr: "Agroalimentaire",
    nameEn: "Food & Agriculture",
    descriptionFr: "Conseil M&A pour l'industrie agroalimentaire, de la production à la distribution.",
    descriptionEn: "M&A advisory for the agri-food industry, from production to distribution.",
    investmentThesisFr: "L'agroalimentaire français bénéficie d'un terroir reconnu mondialement. Les tendances bio, local et premium créent des opportunités de build-up pour les groupes souhaitant accélérer leur développement.",
    investmentThesisEn: "French agri-food benefits from globally recognized terroir. Organic, local, and premium trends create build-up opportunities.",
    iconType: "food",
    referentPartner: "christophe-berthon",
  },
  {
    id: "9",
    slug: "energie-environnement",
    nameFr: "Énergie & environnement",
    nameEn: "Energy & Environment",
    descriptionFr: "Accompagnement des acteurs de la transition énergétique et des services environnementaux.",
    descriptionEn: "Supporting energy transition players and environmental services companies.",
    investmentThesisFr: "La transition énergétique génère une dynamique M&A exceptionnelle. Les énergies renouvelables, l'efficacité énergétique et l'économie circulaire attirent des capitaux massifs et des valorisations premium.",
    investmentThesisEn: "The energy transition is generating exceptional M&A momentum. Renewable energy, energy efficiency, and circular economy attract massive capital.",
    iconType: "energy",
    referentPartner: "martin-egasse",
  },
];

// Enhanced team members with bios (Phase 1 - Roadmap #22)
export const teamMembersEnhanced = teamMembers.map((member) => ({
  ...member,
  bioFr: member.bio,
  // TODO: Add English translations for team member bios
  bioEn: member.bio, // Temporary: using French bio for English until translations are provided
  sectorsExpertise: member.id === "1" ? ["technologies-logiciels", "services-financiers-assurance"] 
    : member.id === "2" ? ["distribution-services-b2b", "agroalimentaire"]
    : member.id === "3" ? ["distribution-services-b2c", "energie-environnement"]
    : member.id === "4" ? ["sante"]
    : member.id === "5" ? ["immobilier-construction"]
    : member.id === "6" ? ["industries"]
    : [],
  transactions: mockDeals
    .filter((_, idx) => idx % 8 === parseInt(member.id) - 1)
    .map((d) => d.slug),
}));

export const SECTORS = [
  "Technologies & logiciels",
  "Distribution & services B2B",
  "Distribution & services B2C",
  "Santé",
  "Immobilier & construction",
  "Industries",
  "Services financiers & assurance",
  "Agroalimentaire",
  "Énergie & environnement",
] as const;
