export const teamMembers = [
  {
    id: "1",
    slug: "gregory-colin",
    name: "Grégory Colin",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/GC_1_-_cropped_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/gregorycolin/",
  },
  {
    id: "2",
    slug: "christophe-berthon",
    name: "Christophe Berthon",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/CB_1_-_cropped_-_alt_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/christophe-berthon-843924118/",
  },
  {
    id: "3",
    slug: "martin-egasse",
    name: "Martin Egasse",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/ME_2_-_cropped_-_alt_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/martinegasse/",
  },
  {
    id: "4",
    slug: "tristan-cossec",
    name: "Tristan Cossec",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/TC_2_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/tristan-cossec-3b5a0247/",
  },
  {
    id: "5",
    slug: "serge-de-fay",
    name: "Serge de Faÿ",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/SF_2_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/serge-de-fa%C3%BF-09713555/",
  },
  {
    id: "6",
    slug: "jerome-berthiau",
    name: "Jérôme Berthiau",
    role: "Associé fondateur",
    photo: "/assets/Equipe_Alecia/JB_1_-_cropped_-_alt_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/jeromeberthiau/",
  },
  {
    id: "7",
    slug: "louise-pini",
    name: "Louise Pini",
    role: "Analyste",
    photo: "/assets/Equipe_Alecia/LP__2__-_cropped.jpg",
    linkedinUrl: "https://www.linkedin.com/in/louise-p-184b7a160/",
  },
  {
    id: "8",
    slug: "mickael-furet",
    name: "Mickael Furet",
    role: "Analyste",
    photo: "/assets/Equipe_Alecia/MF_p1080.jpg",
    linkedinUrl: "https://www.linkedin.com/in/mickael-furet/",
  },
];

export const mockDeals = [
  {
    id: "1",
    slug: "hmr-leclerc",
    clientName: "HMR",
    clientLogo: null,
    acquirerName: "Leclerc - franchisé",
    acquirerLogo: null,
    sector: "Distribution & services B2C",
    region: "Provence-Alpes-Côte d'Azur",
    year: 2022,
    mandateType: "Cession",
    isPriorExperience: false,
  },
  {
    id: "2",
    slug: "safe-group",
    clientName: "Safe Group",
    clientLogo: null,
    acquirerName: "DOGS Security",
    acquirerLogo: null,
    sector: "Distribution & services B2B",
    region: "Île-de-France",
    year: 2024,
    mandateType: "Acquisition",
    isPriorExperience: false,
  },
  {
    id: "3",
    slug: "signes",
    clientName: "Signes",
    clientLogo: null,
    acquirerName: "La/Ba Architectes",
    acquirerLogo: null,
    sector: "Distribution & services B2C",
    region: "Île-de-France",
    year: 2024,
    mandateType: "Cession",
    isPriorExperience: true,
  },
  {
    id: "4",
    slug: "xrl-consulting",
    clientName: "XRL Consulting",
    clientLogo: null,
    acquirerName: "Banque Populaire et Caisse d'Epargne",
    acquirerLogo: null,
    sector: "Distribution & services B2B",
    region: "Île-de-France",
    year: 2023,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "5",
    slug: "kanope",
    clientName: "Kanopé",
    clientLogo: null,
    acquirerName: "Metagram",
    acquirerLogo: null,
    sector: "Services financiers & assurance",
    region: "Occitanie",
    year: 2023,
    mandateType: "Cession",
    isPriorExperience: true,
  },
  {
    id: "6",
    slug: "keller-williams",
    clientName: "Keller Williams",
    clientLogo: null,
    acquirerName: "Entrepreneur Invest",
    acquirerLogo: null,
    sector: "Immobilier & construction",
    region: "Île-de-France",
    year: 2022,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "7",
    slug: "wyz-group",
    clientName: "Wyz Group",
    clientLogo: null,
    acquirerName: "Generis Capital Partners",
    acquirerLogo: null,
    sector: "Technologies & logiciels",
    region: "Hauts-de-France",
    year: 2021,
    mandateType: "Levée de fonds",
    isPriorExperience: true,
  },
  {
    id: "8",
    slug: "finaxy",
    clientName: "Finaxy",
    clientLogo: null,
    acquirerName: "Ardian",
    acquirerLogo: null,
    sector: "Services financiers & assurance",
    region: "Île-de-France",
    year: 2021,
    mandateType: "Cession",
    isPriorExperience: true,
  },
];
